title: So It Goes
description: > # this means to ignore newlines until "baseurl:"
  So It Goes is a blog with some occasional cloud-related posts with a
  focus on Microsoft Azure.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://soitgoes.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:  #if your site has a twitter account, enter it here

# Author Settings
author: Neil Mackenzie # add your name
author-img: clouds.jpg # add your photo
about-author: Cloud Solution Architect at Microsoft # add description
social-twitter: mknz # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: nmackenzie # add your Github handle
social-linkedin: neilmackenziesfo # add your Linkedin handle
social-mastodon: mknz
#social-email: # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
